name = "useful-websites"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "useful-websites-db"
database_id = "e57ad85e-6e94-4cd2-9858-299a93077626" # Random valid UUID for local dev

[vars]
JWT_SECRET = "dev-secret-key-change-in-prod"
ADMIN_SECRET_TOKEN = "dev-admin-token"
